### ISSUE TITLE
queue.client.info is not a function

### ISSUE THREAD

**Issue by armmmo** [vcapretz/bull-board#98] opened 2020-04-23 22:10 UTC
TypeError: queue.client.info is not a function
    at getStats (/Users/macbookpro/Documents/data/node_modules/bull-board/routes/getDataForQeues.js:12:22)
    at getDataForQeues (/Users/macbookpro/Documents/data/node_modules/bull-board/routes/getDataForQeues.js:71:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async handler (/Users/macbookpro/Documents/data/node_modules/bull-board/routes/queues.js:5:5)
TypeError: queue.client.info is not a function
    at getStats (/Users/macbookpro/Documents/data/node_modules/bull-board/routes/getDataForQeues.js:12:22)
    at getDataForQeues (/Users/macbookpro/Documents/data/node_modules/bull-board/routes/getDataForQeues.js:71:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async handler (/Users/macbookpro/Documents/data/node_modules/bull-board/routes/queues.js:5:5)

//////////////////////////////

const { Queue, Worker, QueueEvents } = require('bullmq');

var  cluster = require('cluster');
const { setQueues, UI } = require('bull-board')
const app = require('express')()
const port = 3010

var numWorkers = 8;
var queue = new Queue("Paint");
const queueEvents = new QueueEvents('Paint');

setQueues([queue])

if(cluster.isMaster){
  for (var i = 0; i < numWorkers; i++) {
    cluster.fork();
  }

  cluster.on('online', function(worker) {
    // Lets create a few jobs for the queue workers
    for(var i=0; i<500; i++){
        queue.add('cars', { color: 'blue' });
    };
  });

  cluster.on('exit', function(worker, code, signal) {
    console.log('worker ' + worker.process.pid + ' died');
  });
}else{
    const worker = new Worker('Paint', async job => {
        if (job.name === 'cars') {
          await console.log(job.data.color);
        }
    });
    queueEvents.on('waiting', ({ jobId }) => {
        console.log(`A job with ID ${jobId} is waiting`);
    });

    queueEvents.on('active', ({ jobId, prev }) => {
        console.log(`Job ${jobId} is now active; previous status was ${prev}`);
    });

    queueEvents.on('completed', ({ jobId, returnvalue }) => {
        console.log(`${jobId} has completed and returned ${returnvalue}`);
    });

    queueEvents.on('failed', ({ jobId, failedReason }) => {
        console.log(`${jobId} has failed with reason ${failedReason}`);
    });
}
app.use('/ui', UI)
app.listen(port, () => console.log(`Example app listening at http://localhost:${port}`))

**Comment by vcapretz** [comment] 2020-04-24 15:11
hey 👋, are you using one of the alpha versions or the latest stable one? 

if you're not in the alpha version for bull-board we don't have support for bullmq yet 😄 

in the alpha we do support bullmq but we still need some testing and to align the docs before making it a beta or even a stable release 👍

**Comment by garrett-gottlieb** [comment] 2020-08-06 19:51
@vcapretz can you point to the alpha? happy to test it out.

**Comment by vcapretz** [comment] 2020-08-07 14:50
hey @garrett-gottlieb, the latest alpha version released today was `1.0.0-alpha.9`

you can get it by manually changing it in your `package.json` or use `yarn add bull-board@1.0.0-alpha-9` 😄

**Comment by tangaye** [comment] 2020-09-02 12:15
Same problem here. I tried using, but the UI class doesn't exist.

**Comment by takaaptech** [comment] 2020-09-10 08:25
@tangaye After change it to 1.0.0-alpha.10, you should run npm update
And in the new version, they change back UI to router
https://github.com/vcapretz/bull-board/blob/master/src/index.ts

So let try it, I can run it now

**Comment by tangaye** [comment] 2020-09-11 11:05
Thanks @takaaptech. I looked in the code days ago and figured 'router' was used instead of UI. Thanks again.

**Comment by acro5piano** [comment] 2020-09-16 10:31
I had the same problem and upgrading to `1.0.0-alpha.10` saved my life! Thanks.

**Comment by vcapretz** [comment] 2020-12-16 09:43
hey all 👋 

I'm closing this issue for now, but please let me know and feel free to reopen it if the issue is still happening on version 1.2.0 👍 

thank you!

**Closed by vcapretz** 2020-12-16 09:43 UTC
