### ISSUE TITLE
"queue.getName is not a function" in version 1.1.2 when calling setQueues

### ISSUE THREAD

**Issue by guiquintelas** [vcapretz/bull-board#198] opened 2020-12-11 22:04 UTC
![image](https://user-images.githubusercontent.com/29166076/101958762-b88f9f80-3be2-11eb-93ba-26d1ec83ba11.png)

![image](https://user-images.githubusercontent.com/29166076/101959197-9e09f600-3be3-11eb-8039-bb2f9079210c.png)

bullmq version: 1.10.0

It works in version `1.0.0-beta.1`

**Comment by sbarzaghialteaup** [comment] 2020-12-12 03:08
Seems duplicate of #193 bye

**Closed** 2020-12-12 09:28 UTC
